In [1]:
import torch 
import numpy as np

In [2]:
data = [[5,5],[5,5]]
x_data = torch.tensor(data)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data 
print(f'ones tensor: \n{x_ones}\n')

x_rand = torch.rand_like(x_data,dtype=torch.float)# overrides the datatype of x_data
print(f'Random tensor: \n{x_rand} \n')

ones tensor: 
tensor([[1, 1],
        [1, 1]])

Random tensor: 
tensor([[0.2615, 0.1700],
        [0.5065, 0.2698]]) 



In [5]:
shape = (3,3,3,2,2)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor: \n {rand_tensor} \n')
print(f'Ones Tensor: \n {ones_tensor} \n')
print(f'Zeros Tensor: \n {zeros_tensor}')

Random Tensor: 
 tensor([[[[[0.2109, 0.5406],
           [0.6539, 0.6328]],

          [[0.3493, 0.9838],
           [0.4774, 0.7458]],

          [[0.1512, 0.9623],
           [0.0442, 0.1027]]],


         [[[0.9008, 0.9206],
           [0.1369, 0.8829]],

          [[0.4511, 0.4582],
           [0.9580, 0.4864]],

          [[0.7050, 0.3688],
           [0.8319, 0.9066]]],


         [[[0.3736, 0.7747],
           [0.9444, 0.0301]],

          [[0.5657, 0.0218],
           [0.0790, 0.9039]],

          [[0.8101, 0.0757],
           [0.8296, 0.5299]]]],



        [[[[0.2417, 0.9046],
           [0.1072, 0.7146]],

          [[0.2546, 0.6470],
           [0.8086, 0.2239]],

          [[0.0601, 0.5087],
           [0.3152, 0.9838]]],


         [[[0.6606, 0.1006],
           [0.1639, 0.0867]],

          [[0.1677, 0.3302],
           [0.4192, 0.7368]],

          [[0.5230, 0.9869],
           [0.7876, 0.0505]]],


         [[[0.7571, 0.5263],
           [0.5941, 0.5294]],

          [

In [6]:
# Tensor attributes

tensor = torch.rand(3,4)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor = tensor.to(device)
print(f'shape of tensor: {tensor.shape}')
print(f'data type of tensor: {tensor.dtype}')
print(f'device tensor is stored on: {tensor.device}')

shape of tensor: torch.Size([3, 4])
data type of tensor: torch.float32
device tensor is stored on: cuda:0


In [7]:
tensor = torch.ones(4,4)
tensor[:,2]=0# tensor[row,columns] the : means "give me all the rows: ,2 from those
# rows five me the colmum index 2
print(tensor)

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])


In [11]:
x_shape= [2,2]
x=torch.zeros(x_shape)


In [12]:
x

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
y[]